# Generated by Django 3.0.5 on 2020-05-23 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 23, 13, 55, 39, 647836, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 13, 55, 58, 951918, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
