# Generated by Django 3.0.6 on 2020-05-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200528_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft_state',
            field=models.BooleanField(default=False),
        ),
    ]
